# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonglong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='业务项目')),
            ],
            options={
                'verbose_name_plural': '业务范围',
                'verbose_name': '业务范围',
            },
        ),
    ]
