# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonglong', '0003_auto_20170422_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='content',
            field=models.TextField(blank=True, verbose_name='项目明细'),
        ),
    ]
