# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonglong', '0005_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100, verbose_name='图片描述')),
                ('picture', models.ImageField(upload_to='yonglong/appearance/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '船员风采',
                'verbose_name_plural': '船员风采',
            },
        ),
    ]
